from django.db import models

class CaseLine (models.Model):
    case_id = models.TextField()
    asmo = models.TextField()
    asmo_sent_id = models.TextField()
    sentence_id = models.TextField()
    para_id = models.TextField()
    judge = models.TextField()
    text = models.TextField()
    role = models.TextField()
    significant = models.TextField(null=True, blank=True)
    align = models.TextField(null=True, blank=True)
    outcome = models.TextField(null=True, blank=True)
    fullagr = models.TextField(null=True, blank=True)
    partagr = models.TextField(null=True, blank=True)
    fulldis = models.TextField(null=True, blank=True)
    partdis = models.TextField(null=True, blank=True)
    ackn = models.TextField(null=True, blank=True)
    provision_ent = models.TextField(null=True, blank=True)
    instrument_ent = models.TextField(null=True, blank=True)
    court_ent = models.TextField(null=True, blank=True)
    case_name_ent = models.TextField(null=True, blank=True)
    citation_bl_ent = models.TextField(null=True, blank=True)
    judge_ent = models.TextField(null=True, blank=True)
