# Generated by Django 4.2.1 on 2023-06-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtractedCase',
            new_name='CaseLine',
        ),
    ]
